language: node_js # 声明环境为node
node_js: stable

# Travis-CI Caching
cache:
directories:
- node_modules # 缓存node_modules文件夹

# S: Build Lifecycle
before_install:
- export TZ='Asia/Shanghai' # 更改时区
- npm install hexo-cli -g

install:
- npm install # 下载依赖

script:
- hexo clean
- hexo g


after_script: # 推送到github的部分
- git clone https://${GH_REF} .deploy_git
- cd .deploy_git
- git checkout master
- cd ../
- mv .deploy_git/.git/ ./public/
- cd ./public
- git config user.name "fadaixiaohai"
- git config user.email "271246498@qq.com"
- git add .
- git commit -m "Travis CI Auto Builder at `date +"%Y-%m-%d %H:%M"`"
- git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master

# E: Build LifeCycle
branches:
only:
- hexo # 只对hexo分支构建

env: # 环境变量



